version: '2'
services:
    kudoflash-app:
        image: kudoflash
        external_links:
            - kudoflash-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/kudoflash
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    kudoflash-postgresql:
        extends:
            file: postgresql.yml
            service: kudoflash-postgresql
